repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--config, backend/pyproject.toml]
        files: ^backend/
      - id: ruff-format
        args: [--config, backend/pyproject.toml]
        files: ^backend/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--config-file, backend/pyproject.toml]
        files: ^backend/
        additional_dependencies: ["fastapi"]

  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit
        args: ["--ignore-vuln", "GHSA-6vgw-5pg2-w6jp"]
        files: ^backend/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-c", "backend/pyproject.toml", "-r"]
        files: ^backend/
