name: Feature request
description: Proposer une nouvelle fonctionnalité
labels: ["enhancement"]
body:
  - type: textarea
    id: context
    attributes:
      label: Contexte
      description: Quel problème cette fonctionnalité résout-elle ?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposition
      description: Décris la solution envisagée.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considérées
