"""add project categories

Revision ID: 8895f92000c0
Revises: d85708a00d9a
Create Date: 2026-02-20 16:50:52.793259

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8895f92000c0"
down_revision: str | Sequence[str] | None = "d85708a00d9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projectcategory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_projectcategory_name"), "projectcategory", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_projectcategory_slug"), "projectcategory", ["slug"], unique=True
    )
    with op.batch_alter_table("project") as batch_op:
        batch_op.add_column(sa.Column("category_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_project_category_id", "projectcategory", ["category_id"], ["id"]
        )


# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project") as batch_op:
        batch_op.drop_constraint("fk_project_category_id", type_="foreignkey")
        batch_op.drop_column("category_id")
    op.drop_index(op.f("ix_projectcategory_slug"), table_name="projectcategory")
    op.drop_index(op.f("ix_projectcategory_name"), table_name="projectcategory")
    op.drop_table("projectcategory")
    # ### end Alembic commands ###
