"""replace avatar_url and resume_url with filename fields in profile

Revision ID: 8e7c653cc854
Revises: 8895f92000c0
Create Date: 2026-02-22 14:58:13.841951

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e7c653cc854"
down_revision: str | Sequence[str] | None = "8895f92000c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profile",
        sa.Column(
            "avatar_filename",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
    )
    op.add_column(
        "profile",
        sa.Column(
            "resume_filename",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
    )
    op.drop_column("profile", "avatar_url")
    op.drop_column("profile", "resume_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profile", sa.Column("resume_url", sa.VARCHAR(length=500), nullable=True)
    )
    op.add_column(
        "profile", sa.Column("avatar_url", sa.VARCHAR(length=500), nullable=True)
    )
    op.drop_column("profile", "resume_filename")
    op.drop_column("profile", "avatar_filename")
    # ### end Alembic commands ###
