"""add social links model

Revision ID: c1bedca371d3
Revises: 01b07fb254c9
Create Date: 2026-02-20 14:17:40.846366

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1bedca371d3"
down_revision: str | Sequence[str] | None = "01b07fb254c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sociallink",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "platform", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("profile", "github_url")
    op.drop_column("profile", "linkedin_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profile", sa.Column("linkedin_url", sa.VARCHAR(length=500), nullable=True)
    )
    op.add_column(
        "profile", sa.Column("github_url", sa.VARCHAR(length=500), nullable=True)
    )
    op.drop_table("sociallink")
    # ### end Alembic commands ###
